### ISSUE TITLE
Bullet time management

### ISSUE THREAD

**Issue by rubdos** [kyavuzkurt/Linea-Caelestis#1]
Hi!

Just a friendly note from one of the people behind crabstick: I see that the lichess account is opening quite some rated bullet games, and losing them on time after two/three moves. I'm not sure whether you're aware of this. You may get flagged for sandbagging, which you may want to avoid.

Good luck with the bot!

Ruben

**Comment by rubdos** [comment]
I see some other games where your bot account resigns, e.g. https://lichess.org/nHfcFij7. This behaviour triggered a sandbagging warning on crabstick when we were still developing. You may want to disable rated games until you're more certain about the stability :-)

**Comment by kyavuzkurt** [comment]
Thanks for the feedback! I an trying to figure out lichess API. Sorry if my buggy code caused you inconvenience.

**Comment by rubdos** [comment]
> Sorry if my buggy code caused you inconvenience.

Don't worry about that. We're also sorry if our buggy code causes you inconvenience! Just wanted to give you a heads-up!
